# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "Dependabot"
    open-pull-requests-limit: 5
    target-branch: "main"
    groups:
      spring-dependencies: # Dependabot will create single PR for spring dependencies updates
        patterns:
          - "org.springframework*"
        update-types:
          - "minor"
          - "patch"
          # for major separate PR will be created
      cucumber-dependencies:
        patterns:
          - "io.cucumber*"
    ignore:
      - dependency-name: "org.codehaus.mojo:build-helper-maven-plugin"
        versions: ["[3.5,)"]
      - dependency-name: "org.codehaus.mojo:flatten-maven-plugin"
        versions: [ "[1.6,)" ]
